"""Report rendering — console table via rich, markdown for PR comments."""

from __future__ import annotations

from rich.console import Console
from rich.table import Table

from groundskeeper.models import Finding, Severity, VerdictStatus

_STATUS_ORDER = {
    VerdictStatus.VIOLATION: 0,
    VerdictStatus.UNCERTAIN: 1,
    VerdictStatus.PASS: 2,
    VerdictStatus.NOT_APPLICABLE: 3,
}

_STATUS_STYLE = {
    VerdictStatus.VIOLATION: "[red]VIOLATION[/red]",
    VerdictStatus.UNCERTAIN: "[yellow]UNCERTAIN[/yellow]",
    VerdictStatus.PASS: "[green]PASS[/green]",
    VerdictStatus.NOT_APPLICABLE: "[dim]N/A[/dim]",
}

_STATUS_EMOJI = {
    VerdictStatus.VIOLATION: "❌",
    VerdictStatus.UNCERTAIN: "⚠️",
    VerdictStatus.PASS: "✅",
    VerdictStatus.NOT_APPLICABLE: "➖",
}


def sort_findings(findings: list[Finding]) -> list[Finding]:
    return sorted(findings, key=lambda f: (_STATUS_ORDER[f.status], f.severity != Severity.BLOCKING))


def print_console_report(repo: str, pr_number: int, findings: list[Finding]) -> None:
    console = Console()
    findings = sort_findings(findings)
    violations = [f for f in findings if f.status == VerdictStatus.VIOLATION]
    uncertain = [f for f in findings if f.status == VerdictStatus.UNCERTAIN]

    console.print()
    console.rule(f"[bold]Groundskeeper: {repo}#{pr_number}[/bold]")
    console.print(
        f"  {len(violations)} violation(s), {len(uncertain)} uncertain, "
        f"{len(findings)} rules evaluated"
    )
    console.print()

    table = Table(show_lines=False)
    table.add_column("Status", width=12)
    table.add_column("Rule", style="cyan", max_width=40)
    table.add_column("Evidence", max_width=36)
    table.add_column("Explanation", max_width=60)

    for f in findings:
        if f.status == VerdictStatus.NOT_APPLICABLE:
            continue
        table.add_row(
            _STATUS_STYLE[f.status],
            f.rule_title + (" [dim](det)[/dim]" if f.deterministic else ""),
            f.evidence or "—",
            f.explanation,
        )
    console.print(table)

    for f in violations:
        if f.suggested_fix:
            console.print(f"\n[bold]{f.evidence}[/bold] — suggested fix:")
            console.print(f"  {f.suggested_fix}")
    console.print()


def render_markdown_report(repo: str, pr_number: int, findings: list[Finding]) -> str:
    findings = sort_findings(findings)
    violations = [f for f in findings if f.status == VerdictStatus.VIOLATION]
    uncertain = [f for f in findings if f.status == VerdictStatus.UNCERTAIN]

    lines = [
        "## Groundskeeper compliance report",
        "",
        f"Checked against `.claude/rules` at base ref. "
        f"**{len(violations)} violation(s)**, {len(uncertain)} uncertain, "
        f"{len(findings)} rules evaluated.",
        "",
        "| Status | Rule | Evidence | Explanation |",
        "|---|---|---|---|",
    ]
    for f in findings:
        if f.status == VerdictStatus.NOT_APPLICABLE:
            continue
        evidence = f"`{f.evidence}`" if f.evidence else "—"
        explanation = f.explanation.replace("|", "\\|").replace("\n", " ")
        det = " *(deterministic)*" if f.deterministic else ""
        lines.append(f"| {_STATUS_EMOJI[f.status]} {f.status.value} | {f.rule_title}{det} | {evidence} | {explanation} |")

    fixes = [f for f in violations if f.suggested_fix]
    if fixes:
        lines += ["", "### Suggested fixes", ""]
        for f in fixes:
            lines.append(f"- **{f.evidence}** — {f.suggested_fix}")

    lines += ["", "<sub>Generated by groundskeeper — rules compiled from this repo's own `.claude/rules`.</sub>"]
    return "\n".join(lines)
